name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore ./RecrAgencyApp/RecrAgencyApp.sln
    - name: Build
      run: dotnet build --no-restore ./RecrAgencyApp/RecrAgencyApp.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal ./RecrAgencyApp/RecrAgencyApp.sln
